version: '3'
services:
  redis:
    image: redis:alpine
    container_name: cache
    expose:
      - 6379
  app:
    build: .
    restart: always
    volumes:
      - ./:/usr/app
    links:
      - redis
      - mongo
    environment:
      - PROCESS_COUNT=1
      - PROJECT_ID="11259adf64d84c9e8c3512d279566120"
    ports:
      - "4001:4001"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'