version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    build: .
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      - PROCESS_COUNT:1
    ports:
      - "4001:8081"